import { CompanySettings, Service, Project, Post, TeamMember, Testimonial, Inquiry } from './types';

export const initialSettings: CompanySettings = {
  id: 1,
  company_name: 'CyberTech Computer & Gaming',
  tagline: 'Pusat Rakit PC Gaming, Laptop, Upgrade & Servis Komputer Terpercaya',
  description: 'Pusat belanja kebutuhan komputer, rakit custom PC gaming & workstation bergaransi resmi, upgrade komponen, dan jasa service laptop/komputer oleh teknisi profesional.',
  logo_url: '/images/logo.svg',
  hero_title: 'Rakit PC Impian & Solusi Komputer Terlengkap Bergaransi Resmi',
  hero_subtitle: 'Spesialis rakitan PC gaming custom tanpa bottleneck, laptop bergaransi resmi, upgrade SSD & RAM super cepat, serta service komputer profesional dengan sparepart original.',
  hero_cta_text: 'Konsultasi Rakit PC',
  hero_cta_link: '/contact',
  contact_email: 'sales@cybertechcomputer.co.id',
  contact_phone: '+62 21 6230 1888',
  contact_whatsapp: '+62 813 8899 7722',
  contact_address: 'Harco Mangga Dua Plaza Lt. 2 Blok B No. 12-14, Jl. Mangga Dua Raya, Jakarta Pusat 10730',
  social_facebook: 'https://facebook.com/cybertechcomputer',
  social_instagram: 'https://instagram.com/cybertechcomputer',
  social_linkedin: 'https://linkedin.com/company/cybertechcomputer',
  social_twitter: 'https://x.com/cybertechpc',
};

export const initialServices: Service[] = [
  {
    id: 's1',
    slug: 'rakit-pc-gaming-custom',
    title: 'Rakit PC Gaming & Streaming Custom',
    summary: 'Perakitan komputer gaming dan live streaming sesuai budget dengan racikan seimbang tanpa bottleneck, cable management rapi, dan benchmark stabil.',
    description: 'Kami membantu Anda meracik spesifikasi PC impian dari budget 5 jutaan hingga monster rig 50+ jutaan. Setiap unit dirakit dengan cable management presisi, sirkulasi udara optimal (airflow), pasta termal berkualitas, dan uji stabilitas (stress test) 24 jam sebelum diserahkan.',
    icon: 'Cpu',
    features: [
      'Konsultasi Racikan Bebas Bottleneck',
      'Cable Management Rapi & Airflow Optimal',
      'Stress Test 24 Jam & Benchmark Sebelum Kirim',
      'Garansi Perakitan & Toko 1 Tahun',
    ],
    display_order: 1,
    is_active: true,
  },
  {
    id: 's2',
    slug: 'servis-laptop-pc-desktop',
    title: 'Servis Laptop & Perbaikan PC Desktop',
    summary: 'Perbaikan laptop dan PC mati total, layar blank, bluescreen, engsel rusak, keyboard macet, hingga perbaikan IC power motherboard.',
    description: 'Mengatasi berbagai masalah hardware dan motherboard menggunakan peralatan diagnosa modern (BGA rework station, oscilloscope). Pengecekan awal transparan tanpa biaya tersembunyi, pengerjaan cepat, dan garansi perbaikan hingga 90 hari.',
    icon: 'Wrench',
    features: [
      'Pengecekan Awal Cepat & Transparan',
      'Teknisi Berpengalaman & Bersertifikasi',
      'Suku Cadang & IC Komponen Original',
      'Garansi Perbaikan Hardware hingga 90 Hari',
    ],
    display_order: 2,
    is_active: true,
  },
  {
    id: 's3',
    slug: 'cleaning-repaste-laptop-pc',
    title: 'Deep Cleaning & Ganti Thermal Paste',
    summary: 'Perawatan berkala pembersihan debu heatsink dan penggantian thermal paste kualitas premium untuk mengatasi laptop/PC panas dan berisik.',
    description: 'Suhu laptop atau PC Anda sering mencapai 90-100°C dan kipas berdengung kencang? Layanan deep cleaning membongkar dan membersihkan total debu pada heatsink, kipas, serta mengaplikasikan thermal paste premium (Arctic MX-6, Noctua NT-H2, atau Honeywell PTM7950) agar suhu turun 15-25°C.',
    icon: 'Sparkles',
    features: [
      'Thermal Paste Premium (Arctic / Noctua / PTM7950)',
      'Pembersihan Kipas & Fin Heatsink Menyeluruh',
      'Turunkan Suhu hingga 15-25°C & Bebas Throttling',
      'Bisa Ditunggu (Estimasi 30-45 Menit)',
    ],
    display_order: 3,
    is_active: true,
  },
  {
    id: 's4',
    slug: 'upgrade-ram-ssd-gpu',
    title: 'Upgrade Komponen, RAM & SSD Cepat',
    summary: 'Tingkatkan performa komputer lama Anda menjadi 10x lebih responsif dengan instalasi SSD NVMe cepat dan ekspansi RAM dual-channel.',
    description: 'Laptop atau PC mulai lambat saat multitasking? Kami menyediakan layanan upgrade instan: migrasi dari HDD ke SSD NVMe ultra-cepat, cloning sistem operasi tanpa kehilangan file kerja, upgrade RAM DDR4/DDR5 dual-channel, serta upgrade kartu grafis (GPU) dan power supply bergaransi resmi.',
    icon: 'HardDrive',
    features: [
      'Cloning OS Cepat Tanpa Kehilangan Data',
      'Pilihan SSD NVMe Gen3, Gen4 & Gen5 Bergaransi 5 Tahun',
      'Upgrade RAM DDR4 / DDR5 Dual-Channel',
      'Pemasangan Kartu Grafis & PSU 80+ Gold',
    ],
    display_order: 4,
    is_active: true,
  },
  {
    id: 's5',
    slug: 'instalasi-windows-software',
    title: 'Instalasi OS Windows Original & Optimasi',
    summary: 'Instalasi Windows original resmi, update driver paling stabil, instalasi software kerja/desain, dan pembersihan sistem dari bloatware.',
    description: 'Pastikan sistem operasi Anda berjalan aman dan legal. Kami melayani instalasi Windows 11/10 dengan lisensi original, pengaturan driver hardware terbaru, paket software penting (Office, Adobe Creative Suite, AutoCAD), serta tweaking optimasi performa boot dan gaming.',
    icon: 'FileText',
    features: [
      'Lisensi Windows Original Resmi & Permanen',
      'Update Driver Hardware & BIOS Paling Stabil',
      'Paket Software Desain, Kantor & Gaming Siap Pakai',
      'Tweaking Bebas Bloatware untuk Latensi Terendah',
    ],
    display_order: 5,
    is_active: true,
  },
  {
    id: 's6',
    slug: 'pengadaan-maintenance-kantor',
    title: 'Pengadaan Unit & Maintenance IT Kantor',
    summary: 'Suplai unit PC kantor partai besar, instalasi jaringan LAN/WiFi, server data, dan kontrak pemeliharaan (maintenance) berkala.',
    description: 'Layanan lengkap bagi instansi, kantor swasta, sekolah, dan warnet gaming. Kami melayani pengadaan PC kantor spek hemat daya, instalasi kabel LAN terstruktur, setting router Mikrotik, setup NAS server lokal, serta kontrak servis rutin on-site dengan SLA respons cepat.',
    icon: 'Briefcase',
    features: [
      'Paket Pengadaan PC Kantor Harga Grosir',
      'Instalasi Jaringan LAN Terstruktur & Mikrotik',
      'Kontrak Servis Rutin Bulanan / On-Call Support',
      'Faktur Pajak & Garansi Resmi Distributor',
    ],
    display_order: 6,
    is_active: true,
  },
];

export const initialProjects: Project[] = [
  {
    id: 'prod-1',
    slug: 'pc-gaming-ryzen7-rtx4070ti',
    title: 'PC Gaming Rig Ryzen 7 7800X3D + RTX 4070 Ti Super 16GB',
    category: 'PC Gaming & Streaming',
    client_name: 'Rp 28.500.000 (Garansi Resmi 3 Thn)',
    summary: 'Rig gaming kompetitif siap melibas game 2K/4K 144+ FPS dengan AIO 360mm Liquid Cooler dan casing tempered glass panoramic.',
    description: 'Monster gaming PC rakitan spesialis esport dan game AAA berat: Prosesor AMD Ryzen 7 7800X3D (Gaming CPU terbaik), GPU Nvidia RTX 4070 Ti Super 16GB GDDR6X, RAM 32GB (2x16GB) DDR5 6000MHz RGB, SSD 1TB NVMe PCIe Gen4, Motherboard B650 Gaming WiFi, Power Supply 850W 80+ Gold Modular. Cable management rapi dengan braided sleeve.',
    cover_image: '/images/products/pc-gaming.svg',
    project_url: 'https://wa.me/6281388997722?text=Halo%20CyberTech,%20saya%20tertarik%20dengan%20PC%20Gaming%20Ryzen%207%207800X3D%20RTX%204070%20Ti',
    is_featured: true,
    display_order: 1,
  },
  {
    id: 'prod-2',
    slug: 'pc-rakitan-ryzen5-rx6600',
    title: 'PC Rakitan Best Value Ryzen 5 5600 + RX 6600 8GB',
    category: 'PC Gaming & Streaming',
    client_name: 'Rp 8.750.000 (Best Value 1080p)',
    summary: 'PC rakitan paling laris untuk gaming 1080p lancar di Valorant, CS2, Dota 2, GTA V, dan Genshin Impact dengan konsumsi daya irit.',
    description: 'Pilihan favorit gamer dengan budget bersahabat: Prosesor AMD Ryzen 5 5600 (6 Core / 12 Thread), GPU Radeon RX 6600 8GB GDDR6, RAM 16GB (2x8GB) DDR4 3200MHz Dual Channel, SSD NVMe 512GB M.2, Motherboard B550M, PSU 550W 80+ Bronze, Casing Gaming dengan 3 Fan RGB statis. Siap pakai langsung main!',
    cover_image: '/images/products/pc-value.svg',
    project_url: 'https://wa.me/6281388997722?text=Halo%20CyberTech,%20saya%20tertarik%20dengan%20PC%20Value%20Ryzen%205%205600%20RX%206600',
    is_featured: true,
    display_order: 2,
  },
  {
    id: 'prod-3',
    slug: 'laptop-asus-rog-zephyrus-g14',
    title: 'Laptop Gaming ASUS ROG Zephyrus G14 OLED 3K',
    category: 'Laptop Gaming & Editing',
    client_name: 'Rp 24.999.000 (Garansi ASUS 2 Thn)',
    summary: 'Laptop gaming ultra-ringkas 1.5kg dengan layar memukau OLED 3K 120Hz, bertenaga AMD Ryzen 9 dan RTX 4060 untuk kreator & gamers.',
    description: 'Kombinasi portabilitas dan performa buas: Layar 14 inci ROG Nebula OLED 3K 120Hz dengan akurasi warna 100% DCI-P3, prosesor AMD Ryzen 9 8945HS dengan akselerasi NPU AI, kartu grafis Nvidia RTX 4060 8GB GDDR6, RAM 16GB LPDDR5X 6400MHz, SSD 1TB PCIe 4.0 NVMe, Audio Dolby Atmos quad-speaker, bodi aluminium CNC presisi.',
    cover_image: '/images/products/laptop-gaming.svg',
    project_url: 'https://wa.me/6281388997722?text=Halo%20CyberTech,%20saya%20tertarik%20dengan%20Laptop%20ASUS%20ROG%20Zephyrus%20G14',
    is_featured: true,
    display_order: 3,
  },
  {
    id: 'prod-4',
    slug: 'pc-workstation-i9-rtx4080',
    title: 'PC Workstation 3D Render Core i9-14900K + RTX 4080 16GB',
    category: 'PC Workstation & Kreator',
    client_name: 'Rp 36.500.000 (Spesialis Render 3D & AI)',
    summary: 'Workstation bertenaga dahsyat untuk simulasi arsitektur, rendering Blender/Maya, editing Premiere Pro 8K, dan komputasi AI.',
    description: 'Didesain untuk stabilitas kerja non-stop 24/7: Intel Core i9-14900K (24 Core / 32 Thread), GPU Nvidia RTX 4080 16GB GDDR6X Studio Ready, RAM 64GB (2x32GB) DDR5 5600MHz High-Speed, SSD 2TB Samsung 990 Pro PCIe 4.0 NVMe (Read 7450 MB/s), AIO Liquid Cooler 360mm Premium, PSU 1000W 80+ Gold PCIe 5.0 ATX 3.0.',
    cover_image: '/images/products/pc-workstation.svg',
    project_url: 'https://wa.me/6281388997722?text=Halo%20CyberTech,%20saya%20tertarik%20dengan%20PC%20Workstation%20Core%20i9%20RTX%204080',
    is_featured: false,
    display_order: 4,
  },
  {
    id: 'prod-5',
    slug: 'paket-pc-kasir-kantor-siap-pakai',
    title: 'Paket Komputer Kasir & Bisnis UMKM Siap Pakai',
    category: 'PC Kantor & Kasir',
    client_name: 'Rp 4.650.000 (Paket Lengkap + Printer)',
    summary: 'Paket lengkap toko retail & cafe: PC Core i5 hemat daya, monitor LED, printer kasir thermal Bluetooth, barcode scanner, dan software POS.',
    description: 'Solusi all-in-one tanpa ribet untuk toko Anda: PC Mini Tower Intel Core i5 Quad Core, RAM 8GB DDR4, SSD 256GB super cepat, Monitor LED 19.5" HD, Printer Kasir Thermal 58mm USB/Bluetooth, Barcode Scanner Auto-Scan, Keyboard & Mouse USB, terinstal Windows dan aplikasi kasir gratis tanpa biaya langganan bulanan.',
    cover_image: '/images/products/pc-pos.svg',
    project_url: 'https://wa.me/6281388997722?text=Halo%20CyberTech,%20saya%20tertarik%20dengan%20Paket%20Komputer%20Kasir%20Siap%20Pakai',
    is_featured: false,
    display_order: 5,
  },
  {
    id: 'prod-6',
    slug: 'monitor-gaming-fast-ips-27-180hz',
    title: 'Monitor Gaming Fast IPS 27 Inch 180Hz QHD 2K',
    category: 'Monitor & Periferal',
    client_name: 'Rp 3.250.000 (Garansi Resmi 3 Thn)',
    summary: 'Visual tajam tanpa ghosting dengan panel Fast IPS 2K (2560x1440), refresh rate 180Hz, 1ms respon time, dan 100% sRGB color gamut.',
    description: 'Tingkatkan akurasi dan kenikmatan visual game Anda: Resolusi 2560 x 1440 QHD 2K, Panel Fast IPS dengan viewing angle luas 178°, Refresh Rate 180Hz via DisplayPort, Response Time 1ms GtG, Mendukung AMD FreeSync & Nvidia G-Sync Compatible, HDR400, Port lengkap 2x HDMI 2.0, 1x DP 1.4, Audio Jack, Stand ergonomis dengan tilt adjustment.',
    cover_image: '/images/products/monitor-gaming.svg',
    project_url: 'https://wa.me/6281388997722?text=Halo%20CyberTech,%20saya%20tertarik%20dengan%20Monitor%20Gaming%2027%20Inch%20180Hz',
    is_featured: false,
    display_order: 6,
  },
];

export const initialPosts: Post[] = [
  {
    id: 'b1',
    slug: 'panduan-rakit-pc-gaming-2026-bebas-bottleneck',
    title: 'Panduan Memilih Komponen Rakit PC Gaming 2026 Agar Bebas Bottleneck',
    excerpt: 'Tips mencocokkan prosesor (CPU) dan kartu grafis (GPU) yang seimbang, perhitungan watt power supply (PSU), serta pemilihan motherboard yang tepat.',
    content: `<h2>Mengapa Keseimbangan Komponen Itu Krusial?</h2><p>Salah satu kesalahan paling umum saat merakit PC sendiri adalah mengalokasikan seluruh budget pada kartu grafis (GPU) kelas atas namun memilih prosesor (CPU) atau power supply yang kurang memadai. Hasilnya adalah <strong>bottleneck</strong>, di mana performa GPU tercekik dan terjadi stuttering saat bermain game.</p><h3>1. Pasangkan Prosesor dan GPU Secara Proporsional</h3><p>Jika Anda menggunakan kartu grafis sekelas RTX 4070 Super ke atas, pastikan menggunakan prosesor minimal AMD Ryzen 5 7600 atau Intel Core i5-14600K agar mampu memompa frame rate tinggi tanpa terhambat.</p><h3>2. Jangan Pelit pada Power Supply (PSU)</h3><p>PSU adalah jantung dari keseluruhan komputer. Pilihlah power supply dengan sertifikasi minimal <strong>80+ Bronze</strong> atau <strong>80+ Gold</strong> dari merek terpercaya dengan proteksi lengkap (OVP, UVP, OCP, SCP). Jangan pernah menggunakan PSU bawaan casing murahan untuk komponen bernilai jutaan rupiah.</p><h3>3. Prioritaskan RAM Dual-Channel</h3><p>Gunakan konfigurasi 2 keping RAM (misalnya 2x8GB atau 2x16GB) alih-alih 1 keping tunggal. Mode dual-channel memberikan bandwidth memori hingga dua kali lipat yang sangat terasa pada kelancaran 1% low FPS di game kompetitif.</p>`,
    cover_image: '/images/blog/bottleneck.svg',
    category: 'Panduan & Tips',
    author_name: 'Hendra Wijaya, S.Kom',
    tags: ['Rakit PC', 'Hardware', 'Gaming', 'CPU', 'GPU'],
    status: 'published',
    published_at: '2026-10-06T08:00:00Z',
  },
  {
    id: 'b2',
    slug: 'tanda-laptop-overheating-kapan-ganti-thermal-paste',
    title: 'Tanda-Tanda Laptop Mengalami Overheating dan Waktunya Ganti Thermal Paste',
    excerpt: 'Kenali tanda laptop throttling, kipas berputar kencang tak henti, dan bagaimana deep cleaning serta repaste menurunkan suhu hingga 25°C.',
    content: `<h2>Musuh Terbesar Komponen Elektronik: Panas Berlebih</h2><p>Thermal paste (pasta pendingin) yang mengering adalah penyebab nomor satu mengapa laptop yang awalnya adem perlahan menjadi panas mendidih dan lemot setelah 1-2 tahun pemakaian.</p><h3>Gejala Laptop Anda Mengalami Overheating</h3><ul><li><strong>Kipas Berdengung Kencang:</strong> Kipas pendingin berputar di kecepatan maksimal bahkan saat hanya membuka browser atau dokumen ringan.</li><li><strong>Thermal Throttling:</strong> Frame rate game tiba-tiba drop drastis dari 60 FPS ke 15 FPS setelah bermain 15 menit karena CPU/GPU menurunkan frekuensinya secara darurat demi menghindari kerusakan fisik.</li><li><strong>Bodi Laptop Terasa Membakar Tangan:</strong> Area keyboard dan ventilasi samping terasa sangat panas saat disentuh.</li></ul><p>Solusi terbaik adalah melakukan <em>deep cleaning</em> debu kipas dan mengganti pasta termal lama dengan senyawa konduktivitas tinggi seperti Arctic MX-6 atau thermal pad fase Honeywell PTM7950.</p>`,
    cover_image: '/images/blog/thermal-paste.svg',
    category: 'Perawatan & Servis',
    author_name: 'Dimas Pratama',
    tags: ['Laptop', 'Servis', 'Thermal Paste', 'Cleaning', 'Overheat'],
    status: 'published',
    published_at: '2026-10-03T10:30:00Z',
  },
  {
    id: 'b3',
    slug: 'perbandingan-ssd-nvme-gen3-gen4-gen5',
    title: 'Perbandingan SSD NVMe Gen3, Gen4, dan Gen5: Mana yang Paling Pas untuk Anda?',
    excerpt: 'Memahami perbedaan kecepatan baca/tulis nyata antara PCIe Gen3, Gen4, dan Gen5 agar tidak salah beli sesuai kebutuhan harian.',
    content: `<h2>Bukan Cuma Sekadar Angka Benchmark di Kertas</h2><p>Saat ini di pasaran beredar tiga generasi SSD NVMe M.2: Gen3 (hingga 3.500 MB/s), Gen4 (hingga 7.500 MB/s), dan Gen5 (mencapai 14.000 MB/s). Namun apakah Anda benar-benar membutuhkan yang paling mahal?</p><h3>1. Untuk Kebutuhan Gaming & Harian</h3><p>Perbedaan loading game antara NVMe Gen3 dan Gen4 pada kenyataannya hanya berkisar 0.5 hingga 1 detik. Untuk pengguna umum dan gamer, <strong>NVMe Gen4 kelas menengah</strong> (seperti kecepatan 5.000 MB/s) adalah titik terbaik antara harga dan performa.</p><h3>2. Untuk Video Editor 4K/8K & 3D Render</h3><p>Jika Anda sering memindahkan file footage RAW ratusan gigabyte setiap hari, kecepatan sequential NVMe Gen4 papan atas (seperti Samsung 990 Pro) atau Gen5 akan menghemat waktu transfer Anda secara signifikan.</p><h3>3. Perhatikan Suhu Kerja</h3><p>Semakin tinggi generasi SSD, semakin panas chip pengendalinya (controller). NVMe Gen4 dan Gen5 wajib dilengkapi heatsink pendingin berbahan aluminium tebal agar tidak mengalami thermal throttling saat transfer data besar.</p>`,
    cover_image: '/images/blog/nvme-speed.svg',
    category: 'Review Komponen',
    author_name: 'Alvin Setiawan',
    tags: ['SSD', 'NVMe', 'Storage', 'Upgrade PC', 'Benchmark'],
    status: 'published',
    published_at: '2026-09-29T14:15:00Z',
  },
];

export const initialTeam: TeamMember[] = [
  {
    id: 't1',
    name: 'Hendra Wijaya, S.Kom',
    role: 'Lead System Builder & Hardware Consultant',
    photo_url: '/images/team/hendra.svg',
    bio: 'Pengalaman 10+ tahun dalam arsitektur PC rakitan gaming, tuning overclocking, custom liquid cooling, dan optimalisasi sistem operasi.',
    social_linkedin: 'https://linkedin.com',
    social_twitter: 'https://x.com',
    display_order: 1,
    is_active: true,
  },
  {
    id: 't2',
    name: 'Dimas Pratama',
    role: 'Senior Hardware Repair Technician (BGA Specialist)',
    photo_url: '/images/team/dimas.svg',
    bio: 'Ahli perbaikan motherboard laptop dan kartu grafis level komponen, reballing chipset, dan penanganan mati total bergaransi.',
    social_linkedin: 'https://linkedin.com',
    social_twitter: 'https://x.com',
    display_order: 2,
    is_active: true,
  },
  {
    id: 't3',
    name: 'Alvin Setiawan',
    role: 'Hardware Specialist & Customer Service',
    photo_url: '/images/team/alvin.svg',
    bio: 'Siap membantu konsultasi pemilihan racikan spesifikasi PC seimbang sesuai alokasi dana dan kebutuhan software pengguna.',
    social_linkedin: 'https://linkedin.com',
    social_twitter: 'https://x.com',
    display_order: 3,
    is_active: true,
  },
  {
    id: 't4',
    name: 'Rini Handayani',
    role: 'Procurement & Corporate IT Account Manager',
    photo_url: '/images/team/rini.svg',
    bio: 'Menangani pengadaan partai besar untuk kantor, sekolah, dan warnet gaming dengan faktur pajak dan garansi resmi distributor.',
    social_linkedin: 'https://linkedin.com',
    social_twitter: 'https://x.com',
    display_order: 4,
    is_active: true,
  },
];

export const initialTestimonials: Testimonial[] = [
  {
    id: 'tm1',
    client_name: 'Kevin Ardian',
    client_title: 'Content Creator & Streamer',
    company: 'Jakarta Barat',
    avatar_url: '/images/testimonials/kevin.svg',
    quote: 'Rakit PC Gaming di CyberTech puas banget! Cable management-nya super rapi dari depan sampai belakang, suhu adem, dites benchmark 24 jam sebelum dikirim. Recommended banget buat yang mau PC rapi tanpa repot.',
    rating: 5,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'tm2',
    client_name: 'Jessica Tan',
    client_title: 'Freelance 3D Animator',
    company: 'Tangerang',
    avatar_url: '/images/testimonials/jessica.svg',
    quote: 'Laptop ASUS ROG saya sempat mati total dan divonis ganti motherboard mahal di tempat lain. Dibawa ke CyberTech, teknisi Mas Dimas berhasil ganti IC power-nya dalam 2 hari, data renderan selamat semua dan bergaransi!',
    rating: 5,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'tm3',
    client_name: 'Ir. Bambang Sugiarto',
    client_title: 'Managing Partner',
    company: 'Kantor Notaris & Hukum Sugiarto',
    avatar_url: '/images/testimonials/bambang.svg',
    quote: 'Pesan 12 unit paket PC kantor lengkap dengan monitor dan instalasi jaringan LAN. Pengiriman tepat waktu, semua Windows original, dan support after-salesnya sangat cepat tanggap. Terima kasih CyberTech!',
    rating: 5,
    display_order: 3,
    is_active: true,
  },
];

export const initialInquiries: Inquiry[] = [
  {
    id: 'inq1',
    name: 'Rifki Hidayat',
    email: 'rifki.hidayat@gmail.com',
    phone: '+62 812 3344 5566',
    subject: 'Konsultasi Rakit PC Gaming Budget 15 Juta',
    message: 'Halo mas, saya mau rakit PC gaming untuk main Black Myth: Wukong dan Valorant 144Hz. Budget sekitar 15 jutaan sudah termasuk monitor. Kira-kira rekomendasi racikan prosesor dan VGA-nya apa ya? Terima kasih.',
    status: 'unread',
    created_at: '2026-10-06T09:30:00Z',
  },
  {
    id: 'inq2',
    name: 'dr. Silvia Maharani',
    email: 'silvia.m@klinikmedika.com',
    phone: '+62 818 7766 5544',
    subject: 'Servis Laptop Lenovo Mati Total & Backup Data',
    message: 'Selamat siang, laptop kantor saya merk Lenovo ThinkPad tiba-tiba tidak mau menyala sama sekali setelah kena lonjakan listrik. Di dalamnya ada data penting pasien, apakah bisa dicek dan dibackup datanya hari ini?',
    status: 'read',
    created_at: '2026-10-04T14:10:00Z',
  },
];
