import { CompanySettings, Service, Project, Post, TeamMember, Testimonial, Inquiry } from './types';

export const initialSettings: CompanySettings = {
  id: 1,
  company_name: 'Nusantara Tech Innovasi',
  tagline: 'Mitra Transformasi Digital & Solusi Perangkat Lunak Terdepan',
  description: 'Kami membantu korporasi dan startup berkembang pesat melalui rekayasa perangkat lunak modern, arsitektur cloud serverless, dan kecerdasan buatan terapan.',
  logo_url: '/images/logo.svg',
  hero_title: 'Akselerasi Pertumbuhan Bisnis Anda dengan Solusi Digital Andal',
  hero_subtitle: 'Bangun aplikasi web, mobile, dan sistem enterprise berkinerja tinggi bersama tim insinyur berpengalaman yang berfokus pada hasil nyata.',
  hero_cta_text: 'Mulai Konsultasi',
  hero_cta_link: '/contact',
  contact_email: 'halo@nusantaratech.id',
  contact_phone: '+62 21 5550 9876',
  contact_whatsapp: '+62 812 8899 7700',
  contact_address: 'Sudirman Central Business District (SCBD), Gedung Artha Graha Lt. 24, Jakarta Selatan, 12190',
  social_facebook: 'https://facebook.com/nusantaratech',
  social_instagram: 'https://instagram.com/nusantaratech',
  social_linkedin: 'https://linkedin.com/company/nusantaratech',
  social_twitter: 'https://x.com/nusantaratech',
};

export const initialServices: Service[] = [
  {
    id: 's1',
    slug: 'custom-web-development',
    title: 'Pengembangan Web & SaaS',
    summary: 'Aplikasi web modern berskala enterprise dengan Next.js, React, dan arsitektur serverless yang cepat serta aman.',
    description: 'Kami merancang dan membangun platform web yang responsif, teroptimasi untuk mesin pencari (SEO), dan siap menangani jutaan pengunjung. Mulai dari sistem portal internal, e-commerce skala besar, hingga aplikasi SaaS modern dengan skalabilitas elastis.',
    icon: 'Globe',
    features: ['Next.js & React App Router', 'Arsitektur Serverless & Edge Caching', 'Integrasi API & Payment Gateway', 'Keamanan Tingkat Enterprise'],
    display_order: 1,
    is_active: true,
  },
  {
    id: 's2',
    slug: 'mobile-app-development',
    title: 'Aplikasi Mobile iOS & Android',
    summary: 'Pengalaman mobile native yang intuitif, responsif, dan stabil untuk pengguna Anda di berbagai perangkat.',
    description: 'Pengembangan aplikasi mobile menggunakan teknologi cross-platform performa tinggi seperti Flutter dan React Native. Dibuat dengan antarmuka yang ramah pengguna (UI/UX modern) dan sinkronisasi real-time yang mulus.',
    icon: 'Smartphone',
    features: ['Dukungan Penuh iOS & Android', 'Antarmuka Halus 60-120 FPS', 'Offline-First & Sinkronisasi Data', 'Push Notifications & Analitik'],
    display_order: 2,
    is_active: true,
  },
  {
    id: 's3',
    slug: 'cloud-devops-consulting',
    title: 'Cloud Architecture & DevOps',
    summary: 'Otomatisasi infrastruktur cloud, pipeline CI/CD, dan pemantauan sistem dengan efisiensi biaya optimal.',
    description: 'Migrasikan infrastruktur Anda ke cloud modern (AWS, Google Cloud, Vercel, Supabase) dengan arsitektur microservices atau serverless. Kami mengotomatiskan deployment dan memperkuat keamanan sistem Anda.',
    icon: 'Cloud',
    features: ['Infrastruktur Serverless & Kontainer', 'Pipeline CI/CD Otomatis', 'Pemantauan 24/7 & Alerting', 'Optimasi Biaya Cloud hingga 40%'],
    display_order: 3,
    is_active: true,
  },
  {
    id: 's4',
    slug: 'ai-data-intelligence',
    title: 'AI & Solusi Kecerdasan Buatan',
    summary: 'Integrasi Large Language Models (LLM), otomasi alur kerja cerdas, dan analitik data prediktif.',
    description: 'Bantu tim Anda bekerja lebih cepat dengan asisten cerdas, ekstraksi dokumen otomatis, chatbot interaktif untuk layanan pelanggan, serta model prediksi berbasis data bisnis Anda.',
    icon: 'Sparkles',
    features: ['Integrasi LLM & Agen AI Khusus', 'Otomasi Pemrosesan Dokumen', 'Pencarian Semantik Berbasis Vektor', 'Dashboard Analitik Prediktif'],
    display_order: 4,
    is_active: true,
  },
  {
    id: 's5',
    slug: 'ui-ux-design',
    title: 'Desain UI/UX & Riset Pengguna',
    summary: 'Perancangan antarmuka pengguna yang estetik, mudah digunakan, dan terbukti meningkatkan konversi bisnis.',
    description: 'Kami memadukan riset pengguna mendalam, wireframing, prototyping interaktif, dan Design System yang konsisten agar produk Anda disukai oleh pengguna sejak hari pertama peluncuran.',
    icon: 'Palette',
    features: ['Design System & Komponen Siap Pakai', 'Prototyping Figma Beresolusi Tinggi', 'Uji Kegunaan (Usability Testing)', 'Konversi & UX Audit'],
    display_order: 5,
    is_active: true,
  },
  {
    id: 's6',
    slug: 'cyber-security-audit',
    title: 'Keamanan Siber & Audit Sistem',
    summary: 'Audit keamanan menyeluruh, penetration testing, dan kepatuhan standar data untuk perlindungan maksimal.',
    description: 'Lindungi aset digital dan data sensitif pelanggan Anda dari ancaman siber dengan audit kode sumber, pengetesan celah keamanan, dan implementasi praktik keamanan terbaik.',
    icon: 'ShieldCheck',
    features: ['Vulnerability Assessment & Pen-Testing', 'Enkripsi End-to-End & RLS', 'Review Kepatuhan Privasi Data', 'Rencana Penanggulangan Insiden'],
    display_order: 6,
    is_active: true,
  },
];

export const initialProjects: Project[] = [
  {
    id: 'p1',
    slug: 'fintech-dashboard-platform',
    title: 'Platform Analitik & Portofolio Fintech',
    category: 'Web Development',
    client_name: 'FinTech Nusantara',
    summary: 'Dashboard analitik real-time untuk memantau performa investasi dan transaksi keuangan dengan latensi di bawah 100ms.',
    description: 'Kami membangun sistem analitik terdistribusi dengan visualisasi data interaktif, integrasi open banking API, dan sistem keamanan otentikasi biometrik multi-faktor yang mematuhi regulasi perbankan.',
    cover_image: '/images/projects/fintech.svg',
    project_url: 'https://example.com/project-fintech',
    is_featured: true,
    display_order: 1,
  },
  {
    id: 'p2',
    slug: 'supply-chain-mobile-app',
    title: 'Aplikasi Mobile Pelacakan Armada Logistik',
    category: 'Mobile App',
    client_name: 'Logistik Prima Cargo',
    summary: 'Aplikasi pelacakan pengiriman kurir dan armada kargo dengan GPS real-time dan tanda tangan digital bukti penerimaan.',
    description: 'Platform terintegrasi yang memudahkan pengemudi menerima pesanan dan memungkinkan kantor pusat memantau rute pengiriman secara langsung dengan algoritma efisiensi bahan bakar.',
    cover_image: '/images/projects/logistics.svg',
    project_url: 'https://example.com/project-logistics',
    is_featured: true,
    display_order: 2,
  },
  {
    id: 'p3',
    slug: 'healthcare-telemedicine-portal',
    title: 'Portal Telemedisin & Rekam Medis Elektronik',
    category: 'Web Development',
    client_name: 'Klinik Sehat Terpadu',
    summary: 'Sistem konsultasi dokter online, resep elektronik, dan integrasi rekam medis terenkripsi sesuai standar kesehatan.',
    description: 'Mendukung ribuan pasien berkonsultasi secara aman melalui video call WebRTC terenkripsi, pembayaran instan, dan pengiriman obat otomatis ke alamat pasien.',
    cover_image: '/images/projects/healthcare.svg',
    project_url: 'https://example.com/project-healthcare',
    is_featured: true,
    display_order: 3,
  },
  {
    id: 'p4',
    slug: 'ai-powered-ecommerce-recommendation',
    title: 'Mesin Rekomendasi Cerdas E-Commerce Fashion',
    category: 'AI & Data',
    client_name: 'ModaStyle Retail',
    summary: 'Penerapan AI untuk personalisasi katalog pakaian yang meningkatkan tingkat konversi transaksi sebesar 38%.',
    description: 'Model machine learning yang menganalisis tren belanja pengguna secara real-time dan memberikan saran padu-padan busana yang relevan secara otomatis.',
    cover_image: '/images/projects/ecommerce.svg',
    project_url: 'https://example.com/project-ecommerce',
    is_featured: false,
    display_order: 4,
  },
];

export const initialPosts: Post[] = [
  {
    id: 'b1',
    slug: 'tren-arsitektur-serverless-2026',
    title: 'Mengapa Arsitektur Serverless Menjadi Pilihan Utama Startup & Enterprise',
    excerpt: 'Panduan lengkap mengenai efisiensi biaya, kemudahan skalabilitas, dan keandalan sistem serverless modern berbasis Next.js dan Supabase.',
    content: `<h2>Pengantar Arsitektur Modern</h2><p>Dunia pengembangan aplikasi web telah berkembang pesat. Pola pengelolaan server konvensional yang membutuhkan tim khusus untuk memantau kapasitas CPU dan RAM kini digantikan oleh paradigma <strong>Serverless</strong> dan <strong>Edge Computing</strong>.</p><h3>1. Efisiensi Biaya (Zero Cost at Idle)</h3><p>Dengan serverless, Anda hanya membayar untuk komputasi yang benar-benar digunakan saat ada request masuk. Jika di malam hari lalu lintas pengunjung rendah, biaya operasional pun mendekati nol.</p><h3>2. Skalabilitas Instan</h3><p>Ketika kampanye pemasaran diluncurkan dan terjadi lonjakan pengunjung ribuan kali lipat dalam hitungan menit, platform serverless secara otomatis menggandakan instance fungsi komputasi tanpa downtime.</p><h3>3. Fokus pada Logika Bisnis</h3><p>Para pengembang tidak perlu lagi menghabiskan waktu berjam-jam untuk update kernel sistem operasi, sertifikat SSL manual, atau patch keamanan server. Semua ditangani secara transparan oleh platform seperti Vercel dan Supabase.</p>`,
    cover_image: '/images/blog/serverless.svg',
    category: 'Teknologi',
    author_name: 'Budi Santoso',
    tags: ['Serverless', 'Cloud', 'Next.js', 'Vercel', 'Supabase'],
    status: 'published',
    published_at: '2026-10-05T08:00:00Z',
  },
  {
    id: 'b2',
    slug: 'strategi-keamanan-data-postgresql-rls',
    title: 'Menerapkan Row-Level Security (RLS) di PostgreSQL untuk Keamanan Maksimal',
    excerpt: 'Bagaimana melindungi data multi-tenant dan data sensitif langsung dari level database dengan Row Level Security Supabase.',
    content: `<h2>Keamanan Berlapis di Level Basis Data</h2><p>Banyak celah keamanan terjadi karena pengembang hanya mengandalkan pengecekan otorisasi di level kode aplikasi (backend route). Jika satu baris logika terlewat, data pengguna lain dapat terekspos.</p><h3>Kekuatan Row Level Security (RLS)</h3><p>Row-Level Security pada PostgreSQL memastikan bahwa setiap kueri—baik SELECT, UPDATE, maupun DELETE—hanya dapat mengakses baris data yang memenuhi kondisi kebijakan keamanan yang telah ditentukan di level engine database.</p><blockquote>"Keamanan terbaik adalah keamanan yang tidak bergantung pada asumsi aplikasi semata."</blockquote><p>Dengan mengombinasikan Supabase Auth dan RLS policies, kita dapat membuat aturan deklaratif yang sangat ketat namun mudah dirawat.</p>`,
    cover_image: '/images/blog/security.svg',
    category: 'Keamanan',
    author_name: 'Dewi Anggraini',
    tags: ['PostgreSQL', 'Database', 'Security', 'RLS', 'Supabase'],
    status: 'published',
    published_at: '2026-10-02T10:30:00Z',
  },
  {
    id: 'b3',
    slug: 'meningkatkan-konversi-website-lewat-core-web-vitals',
    title: 'Rahasia Memaksimalkan Core Web Vitals untuk SEO dan Konversi Penjualan',
    excerpt: 'Pelajari cara mengoptimalkan Largest Contentful Paint (LCP), Interaction to Next Paint (INP), dan Cumulative Layout Shift (CLS).',
    content: `<h2>Kecepatan Adalah Kunci Penjualan</h2><p>Studi Google menunjukkan bahwa setiap penundaan 1 detik dalam waktu muat halaman seluler dapat menurunkan tingkat konversi hingga 20%. Di era sekarang, kecepatan bukan lagi nilai tambah opsional, melainkan kebutuhan primer.</p><h3>Tips Praktis Optimasi</h3><ul><li>Gunakan format gambar modern seperti AVIF dan WebP dengan ukuran responsif.</li><li>Terapkan strategi font streaming dan preconnect ke domain penting.</li><li>Gunakan Server Components untuk mengurangi ukuran bundel JavaScript di browser pengunjung.</li></ul>`,
    cover_image: '/images/blog/vitals.svg',
    category: 'Bisnis & Desain',
    author_name: 'Rian Prasetyo',
    tags: ['SEO', 'Web Vitals', 'Performance', 'React'],
    status: 'published',
    published_at: '2026-09-27T14:15:00Z',
  },
];

export const initialTeam: TeamMember[] = [
  {
    id: 't1',
    name: 'Budi Santoso, M.Kom',
    role: 'Chief Executive Officer & Founder',
    photo_url: '/images/team/budi.svg',
    bio: 'Praktisi teknologi dengan pengalaman 15+ tahun memimpin transformasi digital di berbagai korporasi multinasional dan startup unicorn.',
    social_linkedin: 'https://linkedin.com',
    social_twitter: 'https://x.com',
    display_order: 1,
    is_active: true,
  },
  {
    id: 't2',
    name: 'Dewi Anggraini, S.T.',
    role: 'Chief Technology Officer',
    photo_url: '/images/team/dewi.svg',
    bio: 'Pakar arsitektur cloud serverless, keamanan data terdistribusi, dan kecerdasan buatan terapan.',
    social_linkedin: 'https://linkedin.com',
    social_twitter: 'https://x.com',
    display_order: 2,
    is_active: true,
  },
  {
    id: 't3',
    name: 'Rian Prasetyo, B.Des',
    role: 'Head of Product & Design',
    photo_url: '/images/team/rian.svg',
    bio: 'Desainer produk digital peraih penghargaan yang berfokus pada pengalaman pengguna yang intuitif, elegan, dan berdampak nyata.',
    social_linkedin: 'https://linkedin.com',
    social_twitter: 'https://x.com',
    display_order: 3,
    is_active: true,
  },
  {
    id: 't4',
    name: 'Siti Rahmawati',
    role: 'Head of Client Success & Delivery',
    photo_url: '/images/team/siti.svg',
    bio: 'Menjaga hubungan erat dengan mitra bisnis dan memastikan setiap proyek diselesaikan tepat waktu sesuai standar kualitas tinggi.',
    social_linkedin: 'https://linkedin.com',
    social_twitter: 'https://x.com',
    display_order: 4,
    is_active: true,
  },
];

export const initialTestimonials: Testimonial[] = [
  {
    id: 'tm1',
    client_name: 'Ir. Hendra Gunawan',
    client_title: 'Managing Director',
    company: 'PT Samudera Logistik Makmur',
    avatar_url: '/images/testimonials/hendra.svg',
    quote: 'Kolaborasi dengan tim Nusantara Tech Innovasi melampaui ekspektasi kami. Sistem armada logistik yang mereka bangun memangkas waktu operasional hingga 35% dan sangat stabil saat lonjakan pengiriman.',
    rating: 5,
    display_order: 1,
    is_active: true,
  },
  {
    id: 'tm2',
    client_name: 'Clara Wijaya',
    client_title: 'Chief Operating Officer',
    company: 'FinTech Nusa Investa',
    avatar_url: '/images/testimonials/clara.svg',
    quote: 'Platform analitik investasi yang dibangun berjalan dengan sangat cepat dan aman. Kemudahan tim kami mengelola konten dan berita lewat panel CMS-nya sangat membantu produktivitas harian.',
    rating: 5,
    display_order: 2,
    is_active: true,
  },
  {
    id: 'tm3',
    client_name: 'Dr. Michael Salim',
    client_title: 'Direktur Medis',
    company: 'Klinik Sehat Terpadu',
    avatar_url: '/images/testimonials/michael.svg',
    quote: 'Sangat profesional dalam merancang aplikasi telemedisin dengan enkripsi data medis tingkat tinggi. Pasien kami memberikan ulasan sangat positif terhadap kemudahan penggunaannya.',
    rating: 5,
    display_order: 3,
    is_active: true,
  },
];

export const initialInquiries: Inquiry[] = [
  {
    id: 'inq1',
    name: 'Ahmad Fauzi',
    email: 'fauzi@perusahaanmitra.co.id',
    phone: '+62 811 2233 4455',
    subject: 'Rencana Pembuatan Sistem ERP Internal',
    message: 'Halo, perusahaan kami berencana mengembangkan portal web internal untuk manajemen inventaris di 5 cabang. Bisakah kami menjadwalkan diskusi konsultasi minggu ini?',
    status: 'unread',
    created_at: '2026-10-06T09:30:00Z',
  },
  {
    id: 'inq2',
    name: 'Maya Putri',
    email: 'maya.putri@brandretail.com',
    phone: '+62 817 9988 1122',
    subject: 'Pengembangan Aplikasi Mobile E-Commerce',
    message: 'Kami ingin membuat aplikasi mobile berbasis Flutter untuk toko retail fashion kami yang terhubung dengan payment gateway dan sistem kurir otomatis.',
    status: 'read',
    created_at: '2026-10-04T14:10:00Z',
  },
];
